name: MetaFabSwift5
targets:
  MetaFabSwift5:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [MetaFabSwift5]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
