//
// AuthPlayer200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthPlayer200Response: Codable, JSONEncodable, Hashable {

    /** This field has not had a description added. */
    public var id: String?
    /** This field has not had a description added. */
    public var gameId: String?
    /** This field has not had a description added. */
    public var walletId: String?
    /** This field has not had a description added. */
    public var connectedWalletId: String?
    /** This field has not had a description added. */
    public var username: String?
    /** This field has not had a description added. */
    public var accessToken: String?
    /** This field has not had a description added. */
    public var updatedAt: String?
    /** This field has not had a description added. */
    public var createdAt: String?
    public var wallet: WalletModel?

    public init(id: String? = nil, gameId: String? = nil, walletId: String? = nil, connectedWalletId: String? = nil, username: String? = nil, accessToken: String? = nil, updatedAt: String? = nil, createdAt: String? = nil, wallet: WalletModel? = nil) {
        self.id = id
        self.gameId = gameId
        self.walletId = walletId
        self.connectedWalletId = connectedWalletId
        self.username = username
        self.accessToken = accessToken
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.wallet = wallet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case gameId
        case walletId
        case connectedWalletId
        case username
        case accessToken
        case updatedAt
        case createdAt
        case wallet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(gameId, forKey: .gameId)
        try container.encodeIfPresent(walletId, forKey: .walletId)
        try container.encodeIfPresent(connectedWalletId, forKey: .connectedWalletId)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(wallet, forKey: .wallet)
    }
}

