//
// BurnCollectionItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BurnCollectionItemRequest: Codable, JSONEncodable, Hashable {

    /** The quantity of the collectionItemId to burn. */
    public var quantity: Int

    public init(quantity: Int) {
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(quantity, forKey: .quantity)
    }
}

