//
// CollectionItemAttributesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CollectionItemAttributesInner: Codable, JSONEncodable, Hashable {

    /** This field has not had a description added. */
    public var traitType: String?
    public var value: CollectionItemAttributesInnerValue?

    public init(traitType: String? = nil, value: CollectionItemAttributesInnerValue? = nil) {
        self.traitType = traitType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case traitType = "trait_type"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(traitType, forKey: .traitType)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

