//
// CreateCollectionItemRequestAttributesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCollectionItemRequestAttributesInner: Codable, JSONEncodable, Hashable {

    public var traitType: String
    public var value: AnyCodable?

    public init(traitType: String, value: AnyCodable?) {
        self.traitType = traitType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case traitType = "trait_type"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(traitType, forKey: .traitType)
        try container.encode(value, forKey: .value)
    }
}

