//
// CreateCollection200ResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCollection200ResponseAllOf: Codable, JSONEncodable, Hashable {

    public var contract: CreateCollection200ResponseAllOfContract?

    public init(contract: CreateCollection200ResponseAllOfContract? = nil) {
        self.contract = contract
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contract
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contract, forKey: .contract)
    }
}

