//
// CreateProfilePlayerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateProfilePlayerRequest: Codable, JSONEncodable, Hashable {

    /** The username to assign to the created player. */
    public var username: String
    /** A properly formatted permissions object that validates against the MetaFab profile permissions schema. */
    public var permissions: [String: ProfilePermissionsValue]?

    public init(username: String, permissions: [String: ProfilePermissionsValue]? = nil) {
        self.username = username
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}

