//
// CreateCollection200ResponseAllOfContractAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCollection200ResponseAllOfContractAllOf: Codable, JSONEncodable, Hashable {

    public var transactions: [TransactionModel]?

    public init(transactions: [TransactionModel]? = nil) {
        self.transactions = transactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(transactions, forKey: .transactions)
    }
}

