//
// CreateProfileRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateProfileRequest: Codable, JSONEncodable, Hashable {

    /** The profile's username, used to authenticate the profile. Profile usernames are globally unique across MetaFab. There cannot be 2 profiles with the same username created. */
    public var username: String
    /** The password to authenticate as the profile. Additionally, this password is used to encrypt/decrypt a profile's primary wallet and must be provided anytime this profile makes blockchain interactions through various endpoints. */
    public var password: String

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
    }
}

