//
// GetPlayerData200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPlayerData200Response: Codable, JSONEncodable, Hashable {

    public var protectedData: AnyCodable?
    public var publicData: AnyCodable?

    public init(protectedData: AnyCodable? = nil, publicData: AnyCodable? = nil) {
        self.protectedData = protectedData
        self.publicData = publicData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case protectedData
        case publicData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(protectedData, forKey: .protectedData)
        try container.encodeIfPresent(publicData, forKey: .publicData)
    }
}

