//
// GetProfileGames200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetProfileGames200ResponseInner: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var publishedKey: String?
    public var iconImageUrl: String?
    public var coverImageUrl: String?
    public var primaryColorHex: String?
    public var createdAt: String?
    public var players: [PublicPlayer]?

    public init(id: String? = nil, name: String? = nil, publishedKey: String? = nil, iconImageUrl: String? = nil, coverImageUrl: String? = nil, primaryColorHex: String? = nil, createdAt: String? = nil, players: [PublicPlayer]? = nil) {
        self.id = id
        self.name = name
        self.publishedKey = publishedKey
        self.iconImageUrl = iconImageUrl
        self.coverImageUrl = coverImageUrl
        self.primaryColorHex = primaryColorHex
        self.createdAt = createdAt
        self.players = players
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case publishedKey
        case iconImageUrl
        case coverImageUrl
        case primaryColorHex
        case createdAt
        case players
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(publishedKey, forKey: .publishedKey)
        try container.encodeIfPresent(iconImageUrl, forKey: .iconImageUrl)
        try container.encodeIfPresent(coverImageUrl, forKey: .coverImageUrl)
        try container.encodeIfPresent(primaryColorHex, forKey: .primaryColorHex)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(players, forKey: .players)
    }
}

