//
// MintCurrencyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MintCurrencyRequest: Codable, JSONEncodable, Hashable {

    /** The amount of currency to create (mint). */
    public var amount: Double
    /** A valid EVM based address to create (mint) currency for. For example, `0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D`. */
    public var address: String?
    /** Any wallet id within the MetaFab ecosystem to create (mint) currency for. */
    public var walletId: String?

    public init(amount: Double, address: String? = nil, walletId: String? = nil) {
        self.amount = amount
        self.address = address
        self.walletId = walletId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case address
        case walletId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(walletId, forKey: .walletId)
    }
}

