//
// PublicGame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicGame: Codable, JSONEncodable, Hashable {

    /** This field has not had a description added. */
    public var id: String?
    /** This field has not had a description added. */
    public var name: String?
    /** This field has not had a description added. */
    public var publishedKey: String?
    /** This field has not had a description added. */
    public var redirectUris: [String]?
    /** This field has not had a description added. */
    public var iconImageUrl: String?
    /** This field has not had a description added. */
    public var coverImageUrl: String?
    /** This field has not had a description added. */
    public var primaryColorHex: String?
    /** This field has not had a description added. */
    public var updatedAt: String?
    /** This field has not had a description added. */
    public var createdAt: String?

    public init(id: String? = nil, name: String? = nil, publishedKey: String? = nil, redirectUris: [String]? = nil, iconImageUrl: String? = nil, coverImageUrl: String? = nil, primaryColorHex: String? = nil, updatedAt: String? = nil, createdAt: String? = nil) {
        self.id = id
        self.name = name
        self.publishedKey = publishedKey
        self.redirectUris = redirectUris
        self.iconImageUrl = iconImageUrl
        self.coverImageUrl = coverImageUrl
        self.primaryColorHex = primaryColorHex
        self.updatedAt = updatedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case publishedKey
        case redirectUris
        case iconImageUrl
        case coverImageUrl
        case primaryColorHex
        case updatedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(publishedKey, forKey: .publishedKey)
        try container.encodeIfPresent(redirectUris, forKey: .redirectUris)
        try container.encodeIfPresent(iconImageUrl, forKey: .iconImageUrl)
        try container.encodeIfPresent(coverImageUrl, forKey: .coverImageUrl)
        try container.encodeIfPresent(primaryColorHex, forKey: .primaryColorHex)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

