//
// PublicProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicProfile: Codable, JSONEncodable, Hashable {

    /** This field has not had a description added. */
    public var id: String?
    /** This field has not had a description added. */
    public var walletId: String?
    /** This field has not had a description added. */
    public var username: String?
    /** This field has not had a description added. */
    public var updatedAt: String?
    /** This field has not had a description added. */
    public var createdAt: String?
    public var custodialWallet: PublicPlayerCustodialWallet?
    public var wallet: PublicPlayerCustodialWallet?

    public init(id: String? = nil, walletId: String? = nil, username: String? = nil, updatedAt: String? = nil, createdAt: String? = nil, custodialWallet: PublicPlayerCustodialWallet? = nil, wallet: PublicPlayerCustodialWallet? = nil) {
        self.id = id
        self.walletId = walletId
        self.username = username
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.custodialWallet = custodialWallet
        self.wallet = wallet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case walletId
        case username
        case updatedAt
        case createdAt
        case custodialWallet
        case wallet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(walletId, forKey: .walletId)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(custodialWallet, forKey: .custodialWallet)
        try container.encodeIfPresent(wallet, forKey: .wallet)
    }
}

