//
// SetCollectionItemTimelockRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetCollectionItemTimelockRequest: Codable, JSONEncodable, Hashable {

    /** A unix timestamp (in seconds) defining when the set timelock expires. */
    public var timelock: Double

    public init(timelock: Double) {
        self.timelock = timelock
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timelock
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timelock, forKey: .timelock)
    }
}

