//
// SetPlayerConnectedWallet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetPlayerConnectedWallet200Response: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var address: String?
    public var transaction: TransactionModel?

    public init(id: String? = nil, address: String? = nil, transaction: TransactionModel? = nil) {
        self.id = id
        self.address = address
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case address
        case transaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(transaction, forKey: .transaction)
    }
}

