//
// UpdateProfilePlayerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateProfilePlayerRequest: Codable, JSONEncodable, Hashable {

    /** A properly formatted permissions object that validates against the MetaFab profile permissions schema. */
    public var permissions: [String: ProfilePermissionsValue]?

    public init(permissions: [String: ProfilePermissionsValue]? = nil) {
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}

