//
// UpdateProfileRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateProfileRequest: Codable, JSONEncodable, Hashable {

    /** The profile's current password. Must be provided if setting `newPassword`. */
    public var currentPassword: String?
    /** A new password. The profile's old password will no longer be valid. */
    public var newPassword: String?
    /** Revokes the profile's previous access token and returns a new one if true. */
    public var resetAccessToken: Bool?

    public init(currentPassword: String? = nil, newPassword: String? = nil, resetAccessToken: Bool? = nil) {
        self.currentPassword = currentPassword
        self.newPassword = newPassword
        self.resetAccessToken = resetAccessToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentPassword
        case newPassword
        case resetAccessToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentPassword, forKey: .currentPassword)
        try container.encodeIfPresent(newPassword, forKey: .newPassword)
        try container.encodeIfPresent(resetAccessToken, forKey: .resetAccessToken)
    }
}

