//
// UpdateProfilePlayer200ResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateProfilePlayer200ResponseAllOf: Codable, JSONEncodable, Hashable {

    public var wallet: WalletModel?
    public var custodialWallet: WalletModel?

    public init(wallet: WalletModel? = nil, custodialWallet: WalletModel? = nil) {
        self.wallet = wallet
        self.custodialWallet = custodialWallet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case wallet
        case custodialWallet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(wallet, forKey: .wallet)
        try container.encodeIfPresent(custodialWallet, forKey: .custodialWallet)
    }
}

