//
// BurnCurrencyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BurnCurrencyRequest: Codable, JSONEncodable, Hashable {

    /** The amount of currency to remove (burn). The currency balance of the authenticating game or player's wallet must be equal to or greater than this amount. */
    public var amount: Double

    public init(amount: Double) {
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
    }
}

