//
// SetCurrencyFeesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetCurrencyFeesRequest: Codable, JSONEncodable, Hashable {

    /** The recipient address of currency transaction fees. */
    public var recipientAddress: String
    /** A percentage fee for every transaction represented in basis points. To set a 1.5% fee, you would use a value of 150. This value can be 0, denoting no percentage fees. */
    public var basisPoints: Double
    /** A fixed fee for every transaction. A value of 0.5 would mean 0.5 of the currency of a transaction is always taken as a fee. This value can be 0, denoting no fixed fees. */
    public var fixedAmount: Double
    /** The maximum fee amount for any single transaction. The total fee of a transaction is calculated as the sum of the basis points (percentage) fee, and fixed fee. If a calculated fee is greater than this maximum fee value, the maximum fee will be used instead. */
    public var capAmount: Double

    public init(recipientAddress: String, basisPoints: Double, fixedAmount: Double, capAmount: Double) {
        self.recipientAddress = recipientAddress
        self.basisPoints = basisPoints
        self.fixedAmount = fixedAmount
        self.capAmount = capAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipientAddress
        case basisPoints
        case fixedAmount
        case capAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipientAddress, forKey: .recipientAddress)
        try container.encode(basisPoints, forKey: .basisPoints)
        try container.encode(fixedAmount, forKey: .fixedAmount)
        try container.encode(capAmount, forKey: .capAmount)
    }
}

