//
// TransactionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionModel: Codable, JSONEncodable, Hashable {

    /** This field has not had a description added. */
    public var id: String?
    /** This field has not had a description added. */
    public var contractId: String?
    /** This field has not had a description added. */
    public var walletId: String?
    /** This field has not had a description added. */
    public var function: String?
    /** This field has not had a description added. */
    public var args: AnyCodable?
    /** This field has not had a description added. */
    public var hash: String?
    /** This field has not had a description added. */
    public var updatedAt: String?
    /** This field has not had a description added. */
    public var createdAt: String?

    public init(id: String? = nil, contractId: String? = nil, walletId: String? = nil, function: String? = nil, args: AnyCodable? = nil, hash: String? = nil, updatedAt: String? = nil, createdAt: String? = nil) {
        self.id = id
        self.contractId = contractId
        self.walletId = walletId
        self.function = function
        self.args = args
        self.hash = hash
        self.updatedAt = updatedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case contractId
        case walletId
        case function
        case args
        case hash
        case updatedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(contractId, forKey: .contractId)
        try container.encodeIfPresent(walletId, forKey: .walletId)
        try container.encodeIfPresent(function, forKey: .function)
        try container.encodeIfPresent(args, forKey: .args)
        try container.encodeIfPresent(hash, forKey: .hash)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

