//
// WalletModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletModel: Codable, JSONEncodable, Hashable {

    /** This field has not had a description added. */
    public var id: String?
    /** This field has not had a description added. */
    public var address: String?

    public init(id: String? = nil, address: String? = nil) {
        self.id = id
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(address, forKey: .address)
    }
}

